TRUNCATE TABLE CATEGORY;
TRUNCATE TABLE USER;
TRUNCATE TABLE ITEM;

INSERT INTO CATEGORY (NAME, DESCRIPTION) values ('Canned Goods', 'Preserved Foods in Can');

INSERT INTO USER (USER_NAME, USER_ROLE, USER_PASSWORD) values ('Che', 'User', 'Passw0rd');
INSERT INTO USER (USER_NAME, USER_ROLE, USER_PASSWORD) values ('Jay', 'User', 'Passw0rd');
INSERT INTO USER (USER_NAME, USER_ROLE, USER_PASSWORD) values ('Amiya', 'User', 'Passw0rd');
INSERT INTO USER (USER_NAME, USER_ROLE, USER_PASSWORD) values ('Zofia', 'User', 'Passw0rd');

INSERT INTO ITEM (OWNER_ID, NAME, IS_AVAILABLE, CATEGORY_ID) values (3, 'Family Sardines', 0, 0);
INSERT INTO ITEM (OWNER_ID, NAME, IS_AVAILABLE, CATEGORY_ID) values (2, '555 Sardines', 1, 0);
INSERT INTO ITEM (OWNER_ID, NAME, IS_AVAILABLE, CATEGORY_ID) values (3, '555 Sardines', 1, 0);
INSERT INTO ITEM (OWNER_ID, NAME, IS_AVAILABLE, CATEGORY_ID) values (3, 'Mega Sardines', 0, 0);
